### PR TITLE
Add support for the full list of YouTube embedded player parameters

### PR DESCRIPTION
**Pull request by amphibian**
I was looking to just add the `showinfo` parameter, but stumbled across the [full list on the YouTube dev site](https://developers.google.com/youtube/player_parameters#Parameters). Figured it'd be good to just add support for the whole list. I've tested several and they all seem to work.

### CODE REVIEW

**Comment by amphibian** [comment]
Ah, well I completely missed [this pull request](https://github.com/vector/Antenna/pull/20) it seems. Great minds, I suppose? I like this approach because it's comprehensive, and my addition to the README kind of puts the onus on the user to use only those parameters which are supported via HTML5 embeds.

**Comment by mrw** [comment]
Just tried this on a site and it worked well! I think we can merge this. Also, just curious, did you actually check all the params you whitelisted or you just pasted from Google? I've only tried to hide controls and player title so far.

**Comment by amphibian** [comment]
Great. I've tested most of the parameters, yeah, but not all.

**Comment by amphibian** [comment]
Hey Matt, just pinging you on this because I have another pull request ready that I think might be useful (calculating size and ratio of the video, useful for older SD video embeds) - but I can't seems to make another pull request just for those changes (GitHub wants to include all the changes in this pull request as well).

**Comment by mrw** [comment]
Sorry about that! I just merged it. Try now?

**Comment by amphibian** [comment]
Awesome, thanks matt!

**Pull request merged**
